### ISSUE TITLE
Chat room randomly disconnects / splice method doesn't exist?

### ISSUE THREAD

**Issue by albertprk** [albertprk/sconversationsnow#57]
Error message says something about "breaking the rules of hooks". 

Also, it says the method "splice" for useColorScheme.splice doesn't exist. Maybe you could look into that? I uncommented it, but it is in the removeUser method in chatUsers.js.

**Comment by anthonylopes54** [comment]
I need more context regarding the first issue at hand... when does that happen? Have you tried restarting the server? It might be because we're not disconnecting users from the socket. It might also just be a result of modifying the front end while both the frontend and backend are running on localhost (it happened to me a couple of times). With regards to the latter error, that is just a typo. The splice method should be called on the chatUsers list (I think thats what its called). I sent this all on slack this morning (Just figured I'd let you know in case you're not getting the notifications again).

**Comment by albertprk** [comment]
> I need more context regarding the first issue at hand... when does that happen? Have you tried restarting the server? It might be because we're not disconnecting users from the socket. It might also just be a result of modifying the front end while both the frontend and backend are running on localhost (it happened to me a couple of times). With regards to the latter error, that is just a typo. The splice method should be called on the chatUsers list (I think thats what its called). I sent this all on slack this morning (Just figured I'd let you know in case you're not getting the notifications again).

Thanks, that all sounds good. I think it might because of the lack of disconnecting too... we'll figure it out
